### ISSUE TITLE
Unable to tag non main branch

### ISSUE THREAD

**Issue by dmitriykhait** [rickstaa/action-create-tag#9]
I am unable to tag when running the action from branches other then main/master.
```
remote: fatal error in commit_refs        
To https://github.com/XXXXXX
 ! [remote rejected]       11.2.4.1221 -> 11.2.4.1221 (failure)
error: failed to push some refs to 'https://github.com/XXXXXX'
```

Works fine when runs on master, any ideas ?

**Comment by rickstaa** [comment]
@dmitriykhait Sorry for the late reply. I have been very short on time lately. The action should also work on other branches since a git tag is not linked to a branch but a commit (see https://stackoverflow.com/a/27154277/8135687). A working example of this behaviour can be found [here](https://github.com/rickstaa/action-test-repo/actions/runs/2225569932).

I will close this issue for now. Feel free to reply below if you still experience problems.
